### PR TITLE
updated config

### PR DESCRIPTION
**Pull request by michaelkedey**

### CODE REVIEW

**Review by Kattafuah — APPROVED** [review]
cool

**Review by Gina1010 — APPROVED** [review]
good

**Comment by DelaDoreen** [comment]
Good

**Review by DelaDoreen — APPROVED** [review]
good job

**Review by vimray009 — COMMENTED** [review]
Great work guys

**Comment by vimray009** [comment]
great job guys

**Review by seyramgabriel — APPROVED** [review]
Approved. Excellent job by Dela and Michael. The code doesn't lack consistency of flow of thought.

**Review by vimray009 — APPROVED** [review]

**Pull request merged**
